apiVersion: v2
name: router-hosts-operator
description: Kubernetes operator for syncing Ingress hostnames to router-hosts
type: application
version: 0.8.11
appVersion: 0.8.11
home: https://github.com/fzymgc-house/router-hosts
sources:
  - https://github.com/fzymgc-house/router-hosts
maintainers:
  - name: router-hosts maintainers
    url: https://github.com/fzymgc-house/router-hosts
keywords:
  - dns
  - operator
  - ingress
  - networking
