{{- $leaderElectionEnabled := .Values.leaderElection.enabled -}}
{{- if and (not (hasKey .Values.leaderElection "enabled")) (ge (int .Values.replicaCount) 2) -}}
  {{- $leaderElectionEnabled = true -}}
{{- end -}}
{{- if and .Values.rbac.create $leaderElectionEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "router-hosts-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "router-hosts-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "router-hosts-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "router-hosts-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
